/**
 * @fileoverview Mock data for the CloudZoo Inventory Reorder Prediction System.
 * Two textile orders with 6 items each, pre-filled for demo.
 */

export const UNITS = {
    KG: 'kg',
    SPOOLS: 'spools',
    PCS: 'pcs',
    LTRS: 'ltrs',
    MTRS: 'mtrs',
};

export const INITIAL_ORDERS = [
    {
        id: 'TTP-2401',
        customer: 'Prabhu Textiles',
        date: '2026-02-15',
        status: 'In Progress',
        items: [
            {
                id: 'item-1',
                name: 'Cotton Fabric (40s Count)',
                unit: UNITS.KG,
                plannedQty: 100,
                plannedRate: 250,
                actualQty: 110,
                actualRate: 260,
                minStock: 50,
                currentStock: 35,
            },
            {
                id: 'item-2',
                name: 'Stitching Thread',
                unit: UNITS.SPOOLS,
                plannedQty: 50,
                plannedRate: 45,
                actualQty: 48,
                actualRate: 45,
                minStock: 20,
                currentStock: 22,
            },
            {
                id: 'item-3',
                name: 'Buttons (20mm)',
                unit: UNITS.PCS,
                plannedQty: 2000,
                plannedRate: 1.5,
                actualQty: 2100,
                actualRate: 1.5,
                minStock: 500,
                currentStock: 380,
            },
            {
                id: 'item-4',
                name: 'Reactive Dye (Navy)',
                unit: UNITS.LTRS,
                plannedQty: 25,
                plannedRate: 320,
                actualQty: 23,
                actualRate: 340,
                minStock: 10,
                currentStock: 12,
            },
            {
                id: 'item-5',
                name: 'Elastic Band (12mm)',
                unit: UNITS.MTRS,
                plannedQty: 200,
                plannedRate: 8,
                actualQty: 195,
                actualRate: 8,
                minStock: 80,
                currentStock: 65,
            },
            {
                id: 'item-6',
                name: 'Woven Labels',
                unit: UNITS.PCS,
                plannedQty: 3000,
                plannedRate: 2.2,
                actualQty: 3000,
                actualRate: 2.4,
                minStock: 1000,
                currentStock: 850,
            },
        ],
    },
    {
        id: 'TTP-2402',
        customer: 'Lakshmi Garments',
        date: '2026-02-20',
        status: 'Completed',
        items: [
            {
                id: 'item-7',
                name: 'Cotton Fabric (40s Count)',
                unit: UNITS.KG,
                plannedQty: 150,
                plannedRate: 250,
                actualQty: 145,
                actualRate: 255,
                minStock: 50,
                currentStock: 35,
            },
            {
                id: 'item-8',
                name: 'Stitching Thread',
                unit: UNITS.SPOOLS,
                plannedQty: 75,
                plannedRate: 45,
                actualQty: 80,
                actualRate: 44,
                minStock: 20,
                currentStock: 22,
            },
            {
                id: 'item-9',
                name: 'Buttons (15mm)',
                unit: UNITS.PCS,
                plannedQty: 3000,
                plannedRate: 1.2,
                actualQty: 2850,
                actualRate: 1.2,
                minStock: 500,
                currentStock: 620,
            },
            {
                id: 'item-10',
                name: 'Reactive Dye (Black)',
                unit: UNITS.LTRS,
                plannedQty: 30,
                plannedRate: 310,
                actualQty: 32,
                actualRate: 315,
                minStock: 10,
                currentStock: 8,
            },
            {
                id: 'item-11',
                name: 'Elastic Band (12mm)',
                unit: UNITS.MTRS,
                plannedQty: 300,
                plannedRate: 8,
                actualQty: 290,
                actualRate: 8.5,
                minStock: 80,
                currentStock: 65,
            },
            {
                id: 'item-12',
                name: 'Printed Labels',
                unit: UNITS.PCS,
                plannedQty: 4500,
                plannedRate: 1.8,
                actualQty: 4500,
                actualRate: 1.8,
                minStock: 1000,
                currentStock: 1200,
            },
        ],
    },
];
